# Generated by Django 3.1.7 on 2021-03-15 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Panstwo')),
                ('regions', models.CharField(max_length=150, verbose_name='Region')),
                ('city', models.CharField(max_length=150, verbose_name='Miasto')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji')),
                ('delivery_date', models.DateTimeField(verbose_name='Data dostawy')),
                ('price', models.FloatField(verbose_name='Cena')),
                ('is_free', models.BooleanField(default=True, verbose_name='Czy dostempny')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='Czy dostarczony')),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_location', to='transportation_car.location')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL, verbose_name='kierowca')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_location', to='transportation_car.location')),
            ],
        ),
    ]
