# Generated by Django 3.1.7 on 2021-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0002_auto_20210315_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Lokalizacja', 'verbose_name_plural': 'Lokalizacje'},
        ),
        migrations.AlterModelOptions(
            name='transportation',
            options={'verbose_name': 'Transportacja', 'verbose_name_plural': 'Transportacji'},
        ),
        migrations.AddField(
            model_name='transportation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Opis'),
        ),
    ]
