# Generated by Django 3.1.7 on 2021-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0003_auto_20210316_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='is_delivery',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='is_free',
        ),
        migrations.AddField(
            model_name='transportation',
            name='currency',
            field=models.CharField(default=None, max_length=3, verbose_name='Currence'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='data_end_deliveri',
            field=models.DateTimeField(default=None, verbose_name='Koniec terminu dostawy'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='data_end_shipment',
            field=models.DateTimeField(default=None, verbose_name='Koniec terminu nadania'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='data_start_deliveri',
            field=models.DateTimeField(default=None, verbose_name='Poczotek terminu dostawy'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='data_start_shipment',
            field=models.DateTimeField(default=None, verbose_name='Poczotek terminu nadania'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='delivery_location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='start_location',
            field=models.CharField(max_length=1000),
        ),
    ]
