# Generated by Django 3.1.7 on 2021-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0007_auto_20210420_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='model',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Marka i model'),
        ),
    ]
