# Generated by Django 3.1.7 on 2021-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0008_transportation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCar', models.CharField(max_length=100, verbose_name='Data publikacji')),
            ],
            options={
                'verbose_name': 'Rodzai samochoduw',
                'verbose_name_plural': 'Rodzaj samochodu',
            },
        ),
    ]
