# Generated by Django 3.1.7 on 2021-04-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0009_typecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='typeCar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_car', to='transportation_car.typecar'),
        ),
    ]
