# Generated by Django 3.1.7 on 2021-04-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0010_transportation_typecar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='currency',
            field=models.CharField(default=None, max_length=3, verbose_name='Waluta'),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='typeCar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='car', to='transportation_car.typecar', verbose_name='Rodzaj samochodu'),
        ),
    ]
