# Generated by Django 3.1.7 on 2021-04-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0011_auto_20210420_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='car_owner',
        ),
    ]
