# Generated by Django 3.1.7 on 2021-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0013_transportation_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d/', verbose_name='Foto'),
        ),
    ]
