# Generated by Django 3.1.7 on 2021-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation_car', '0014_transportation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images_car/%y/%m/%d/', verbose_name='Image'),
        ),
    ]
