# Generated by Django 3.1.7 on 2021-03-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210316_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='number_of_phon',
            new_name='number_of_phone',
        ),
    ]
