# Generated by Django 3.1.7 on 2021-04-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.driver'),
        ),
    ]
